/vesc_to_odom_node:
  ros__parameters:
    base_frame: base_link
    odom_frame: odom
    publish_tf: true
    speed_to_erpm_gain: 4614.0
    speed_to_erpm_offset: 0.2
    steering_angle_to_servo_gain: -1.2135
    steering_angle_to_servo_offset: 0.5304
    use_servo_cmd_to_calc_angular_velocity: true
    use_sim_time: false
    wheelbase: 0.25
